### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by pengyiwu** [vsharma8363/WestDrive#1]
Hello,i have seen the road lane detection and tracking video provided by Sanjay chan on youtube.
It's same as your test video.So the test .mp4 is your lane detection output? And i only see a LaneDetection.py. Have you completed the code ?
Thank you so much.  Have a nice day!

**Comment by vsharma8363** [comment]
@pengyiwu the video I got off that youtube channel, I was using it as test footage to experiment on the accuracy of my code on detecting lanes. I used the video of the green lines because that was the best footage I could find of clearly divided lanes. I plan to use this on my own vehicle to test on American roads, which have clearly defined lines. Once I used the footage from Sanjay chan to get my lane detection working, I tested it on American roads and have found it to be pretty effective on highways, less so on residential roads. The code is not by any means finished, but I do not plan on making it any more advanced than highway detection any time soon.

**Comment by pengyiwu** [comment]
Thanks,I understand what you mean
